In [66]:
import numpy as np
import random
np.__version__

'1.18.5'

In [79]:
#create two arrays of points
set1=np.array([3,7,11,5,8,10,2,25,30,15,42,0], dtype='float32')
np.random.seed(2)
set2=np.random.randint(0,50,(3,3))
print('Point set 1\n',set1,'\n','Point set 2\n', set2)

Point set 1
 [ 3.  7. 11.  5.  8. 10.  2. 25. 30. 15. 42.  0.] 
 Point set 2
 [[40 15 45]
 [ 8 22 43]
 [18 11 40]]


In [80]:
#attribute, slice, reshape, combine
print('Dimensions in set 2: ',np.ndim(set2))
set3=set2[1,:]
print('Array created from the middle row of set2\n',set3)
print('Set 2 in a 1 dimensional format\n',set2.reshape(9,))
print('Set 2 added to the bottom of set 3\n',np.vstack([set3,set2]))

Dimensions in set 2:  2
Array created from the middle row of set2
 [ 8 22 43]
Set 2 in a 1 dimensional format
 [40 15 45  8 22 43 18 11 40]
Set 2 added to the bottom of set 3
 [[ 8 22 43]
 [40 15 45]
 [ 8 22 43]
 [18 11 40]]


In [81]:
#total/avg/curved/max points
np.add(set1,10,out=set1)
print('Curved Point Set 1:',set1)
print('Total points:',np.sum(set1))
print('Average points:',np.mean(set1))
print('Max points from each row of set 2:',set2.max(axis=1))

Curved Point Set 1: [13. 17. 21. 15. 18. 20. 12. 35. 40. 25. 52. 10.]
Total points: 278.0
Average points: 23.166666
Max points from each row of set 2: [45 43 40]


In [84]:
#point multiplier,non-zeros,etc
mult=np.eye(12,1)
#print('Multiplier 1\n',mult,)
set1=set1*mult
print('Set 1*Multiplier = \n',set1,)
#11 rows are added beneath the inital row of set1 while the multiplier is padded
# to the left of its initial column (with more columns) so both become 12X12
mult2=mult[:3]
#only keeps the first 3 rows of mult
print('Set 2*Multiplier 2 =\n',set2*mult2)

Set 1*Multiplier = 
 [[13. 17. 21. 15. 18. 20. 12. 35. 40. 25. 52. 10.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
Set 2*Multiplier 2 =
 [[40. 15. 45.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [85]:
#(number of) values above cutoff, total above
print('Point set 2:\n',set2)
print('There are values above the 25 point cutoff:',np.any(set2>25))
print('Boolean version of the set:\n',set2>25)
print('Number of values above the cutoff:',np.sum(set2>25))
print('Values above the cutoff:',set2[set2>25])

Point set 2:
 [[40 15 45]
 [ 8 22 43]
 [18 11 40]]
There are values above the 25 point cutoff: True
Boolean version of the set:
 [[ True False  True]
 [False False  True]
 [False False  True]]
Number of values above the cutoff: 4
Values above the cutoff: [40 45 43 40]


In [91]:
#display values at false indexes,change certain values in modified set1
falseRowIndexes=[0,1,1,2,2]
falseColumnIndexes=[1,0,1,0,1]
print('Values below the 25 point cutoff:',set2[falseRowIndexes,falseColumnIndexes])
#print(set1)
set1[1:,[1,3,5,7,9,11]]=-1
print('Set 1 but every other column below the first row has a value=-1\n',set1)

Values below the 25 point cutoff: [15  8 22 18 11]
Set 1 but every other column below the first row has a value=-1
 [[13. 17. 21. 15. 18. 20. 12. 35. 40. 25. 52. 10.]
 [ 0. -1.  0. -1.  0. -1.  0. -1.  0. -1.  0. -1.]
 [ 0. -1.  0. -1.  0. -1.  0. -1.  0. -1.  0. -1.]
 [ 0. -1.  0. -1.  0. -1.  0. -1.  0. -1.  0. -1.]
 [ 0. -1.  0. -1.  0. -1.  0. -1.  0. -1.  0. -1.]
 [ 0. -1.  0. -1.  0. -1.  0. -1.  0. -1.  0. -1.]
 [ 0. -1.  0. -1.  0. -1.  0. -1.  0. -1.  0. -1.]
 [ 0. -1.  0. -1.  0. -1.  0. -1.  0. -1.  0. -1.]
 [ 0. -1.  0. -1.  0. -1.  0. -1.  0. -1.  0. -1.]
 [ 0. -1.  0. -1.  0. -1.  0. -1.  0. -1.  0. -1.]
 [ 0. -1.  0. -1.  0. -1.  0. -1.  0. -1.  0. -1.]
 [ 0. -1.  0. -1.  0. -1.  0. -1.  0. -1.  0. -1.]]


In [92]:
#sort along the axis then partition
print('Set 1 after sorting along its rows\n',np.sort(set1,axis=1))
print('The smallest value from every row in set2\n',np.partition(set2,1,axis=1))

Set 1 after sorting along its rows
 [[10. 12. 13. 15. 17. 18. 20. 21. 25. 35. 40. 52.]
 [-1. -1. -1. -1. -1. -1.  0.  0.  0.  0.  0.  0.]
 [-1. -1. -1. -1. -1. -1.  0.  0.  0.  0.  0.  0.]
 [-1. -1. -1. -1. -1. -1.  0.  0.  0.  0.  0.  0.]
 [-1. -1. -1. -1. -1. -1.  0.  0.  0.  0.  0.  0.]
 [-1. -1. -1. -1. -1. -1.  0.  0.  0.  0.  0.  0.]
 [-1. -1. -1. -1. -1. -1.  0.  0.  0.  0.  0.  0.]
 [-1. -1. -1. -1. -1. -1.  0.  0.  0.  0.  0.  0.]
 [-1. -1. -1. -1. -1. -1.  0.  0.  0.  0.  0.  0.]
 [-1. -1. -1. -1. -1. -1.  0.  0.  0.  0.  0.  0.]
 [-1. -1. -1. -1. -1. -1.  0.  0.  0.  0.  0.  0.]
 [-1. -1. -1. -1. -1. -1.  0.  0.  0.  0.  0.  0.]]
The smallest value from every row in set2
 [[15 40 45]
 [ 8 22 43]
 [11 18 40]]


In [94]:
structure=np.dtype([('points', 'i4'), ('multiplier', 'i4')])
scorebook=np.zeros(3,dtype=structure)
scorebook['points']=set3
scorebook['multiplier']=[2,4,8]
print('Scorebook',scorebook)
print('Points greater than ten',scorebook[scorebook['points']>10])
scorebookRecord=scorebook.view(np.recarray)
print('Points greater than ten(using a record array)',scorebookRecord[scorebookRecord.points>10])

Scorebook [( 8, 2) (22, 4) (43, 8)]
Points greater than ten [(22, 4) (43, 8)]
Points greater than ten(using a record array) [(22, 4) (43, 8)]
